"""Initial schema

Revision ID: e5949cbd4c0b
Revises: 
Create Date: 2020-03-31 23:52:07.337473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5949cbd4c0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Enum('< 10', '< 250', '< 500', '< 1000', '1000+', name='companysize'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('university',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('universityName', sa.String(length=255), nullable=False),
    sa.Column('courseTitle', sa.String(length=255), nullable=False),
    sa.Column('focusArea', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['universityName'], ['university.name'], ),
    sa.PrimaryKeyConstraint('id', 'universityName')
    )
    op.create_table('graduated',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('gradDate', sa.Date(), nullable=False),
    sa.Column('degree', sa.Enum('associates', 'bachelors', 'masters', 'phd', name='degreetype'), nullable=True),
    sa.Column('major', sa.String(length=255), nullable=True),
    sa.Column('gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['university'], ['university.name'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userID', 'university', 'gradDate')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employerID', sa.Integer(), nullable=False),
    sa.Column('jobTitle', sa.String(length=50), nullable=True),
    sa.Column('focusArea', sa.String(length=255), nullable=True),
    sa.Column('minSalary', sa.Integer(), nullable=True),
    sa.Column('maxSalary', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employerID'], ['employer.id'], ),
    sa.PrimaryKeyConstraint('id', 'employerID')
    )
    op.create_table('enrollment',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('courseID', sa.Integer(), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['courseID'], ['course.id'], ),
    sa.ForeignKeyConstraint(['university'], ['university.name'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userID', 'courseID', 'university')
    )
    op.create_table('experience',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('employerID', sa.Integer(), nullable=False),
    sa.Column('jobTitle', sa.String(length=50), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('intern', 'co_op', 'research', 'part_time', 'full_time', name='jobtype'), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['employerID'], ['employer.id'], ),
    sa.ForeignKeyConstraint(['jobTitle'], ['position.jobTitle'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userID', 'employerID', 'jobTitle')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience')
    op.drop_table('enrollment')
    op.drop_table('position')
    op.drop_table('graduated')
    op.drop_table('course')
    op.drop_table('user')
    op.drop_table('university')
    op.drop_table('employer')
    # ### end Alembic commands ###
